### PR TITLE
Resolve Addons

### PR DESCRIPTION
**Pull request by Haselnussbomber**
This adds support to resolve Addons with `<Addon(id)>` or `<Addon(name)>`.

### CODE REVIEW

**Comment by Haselnussbomber** [comment]
Side note: I noticed that agents have to have "Agent" in their name (`<Agent(AgentScenarioTree)>`) but addons don't have to have "Addon" in their name (`<Addon(ScenarioTree)>`).
Perhaps agents should also resolve with just `<Agent(ScenarioTree)>`.

**Comment by pohky** [comment]
you can simplify this by calling `AtkUnitManager.Update()` and then using `AtkUnitManager.TryGetAddonByName()` or `TryGetAddonById`
for the agents i just thought it'd be easier/clearer to just use the plain class name as defined in data.yml

**Comment by Haselnussbomber** [comment]
Yeah, I thought about calling `AtkUnitManager.Update()`, but wanted to avoid the overhead of regenerating the `AtkUnitManager.Addons` List every call, even if it doesn't match the addon regexes. I guess it's not a big deal though. 🤷‍♂️

**Comment by Haselnussbomber** [comment]
How about this? 🙂

**Pull request merged**
